/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// node_modules/parse-ms/index.js
var require_parse_ms = __commonJS({
  "node_modules/parse-ms/index.js"(exports, module2) {
    "use strict";
    module2.exports = (milliseconds) => {
      if (typeof milliseconds !== "number") {
        throw new TypeError("Expected a number");
      }
      const roundTowardsZero = milliseconds > 0 ? Math.floor : Math.ceil;
      return {
        days: roundTowardsZero(milliseconds / 864e5),
        hours: roundTowardsZero(milliseconds / 36e5) % 24,
        minutes: roundTowardsZero(milliseconds / 6e4) % 60,
        seconds: roundTowardsZero(milliseconds / 1e3) % 60,
        milliseconds: roundTowardsZero(milliseconds) % 1e3,
        microseconds: roundTowardsZero(milliseconds * 1e3) % 1e3,
        nanoseconds: roundTowardsZero(milliseconds * 1e6) % 1e3
      };
    };
  }
});

// node_modules/pretty-ms/index.js
var require_pretty_ms = __commonJS({
  "node_modules/pretty-ms/index.js"(exports, module2) {
    "use strict";
    var parseMilliseconds = require_parse_ms();
    var pluralize = (word, count) => count === 1 ? word : `${word}s`;
    var SECOND_ROUNDING_EPSILON = 1e-7;
    module2.exports = (milliseconds, options = {}) => {
      if (!Number.isFinite(milliseconds)) {
        throw new TypeError("Expected a finite number");
      }
      if (options.colonNotation) {
        options.compact = false;
        options.formatSubMilliseconds = false;
        options.separateMilliseconds = false;
        options.verbose = false;
      }
      if (options.compact) {
        options.secondsDecimalDigits = 0;
        options.millisecondsDecimalDigits = 0;
      }
      const result = [];
      const floorDecimals = (value, decimalDigits) => {
        const flooredInterimValue = Math.floor(value * 10 ** decimalDigits + SECOND_ROUNDING_EPSILON);
        const flooredValue = Math.round(flooredInterimValue) / 10 ** decimalDigits;
        return flooredValue.toFixed(decimalDigits);
      };
      const add = (value, long, short, valueString) => {
        if ((result.length === 0 || !options.colonNotation) && value === 0 && !(options.colonNotation && short === "m")) {
          return;
        }
        valueString = (valueString || value || "0").toString();
        let prefix;
        let suffix;
        if (options.colonNotation) {
          prefix = result.length > 0 ? ":" : "";
          suffix = "";
          const wholeDigits = valueString.includes(".") ? valueString.split(".")[0].length : valueString.length;
          const minLength = result.length > 0 ? 2 : 1;
          valueString = "0".repeat(Math.max(0, minLength - wholeDigits)) + valueString;
        } else {
          prefix = "";
          suffix = options.verbose ? " " + pluralize(long, value) : short;
        }
        result.push(prefix + valueString + suffix);
      };
      const parsed = parseMilliseconds(milliseconds);
      add(Math.trunc(parsed.days / 365), "year", "y");
      add(parsed.days % 365, "day", "d");
      add(parsed.hours, "hour", "h");
      add(parsed.minutes, "minute", "m");
      if (options.separateMilliseconds || options.formatSubMilliseconds || !options.colonNotation && milliseconds < 1e3) {
        add(parsed.seconds, "second", "s");
        if (options.formatSubMilliseconds) {
          add(parsed.milliseconds, "millisecond", "ms");
          add(parsed.microseconds, "microsecond", "\xB5s");
          add(parsed.nanoseconds, "nanosecond", "ns");
        } else {
          const millisecondsAndBelow = parsed.milliseconds + parsed.microseconds / 1e3 + parsed.nanoseconds / 1e6;
          const millisecondsDecimalDigits = typeof options.millisecondsDecimalDigits === "number" ? options.millisecondsDecimalDigits : 0;
          const roundedMiliseconds = millisecondsAndBelow >= 1 ? Math.round(millisecondsAndBelow) : Math.ceil(millisecondsAndBelow);
          const millisecondsString = millisecondsDecimalDigits ? millisecondsAndBelow.toFixed(millisecondsDecimalDigits) : roundedMiliseconds;
          add(
            Number.parseFloat(millisecondsString, 10),
            "millisecond",
            "ms",
            millisecondsString
          );
        }
      } else {
        const seconds = milliseconds / 1e3 % 60;
        const secondsDecimalDigits = typeof options.secondsDecimalDigits === "number" ? options.secondsDecimalDigits : 1;
        const secondsFixed = floorDecimals(seconds, secondsDecimalDigits);
        const secondsString = options.keepDecimalsOnWholeSeconds ? secondsFixed : secondsFixed.replace(/\.0+$/, "");
        add(Number.parseFloat(secondsString, 10), "second", "s", secondsString);
      }
      if (result.length === 0) {
        return "0" + (options.verbose ? " milliseconds" : "ms");
      }
      if (options.compact) {
        return result[0];
      }
      if (typeof options.unitCount === "number") {
        const separator = options.colonNotation ? "" : " ";
        return result.slice(0, Math.max(options.unitCount, 1)).join(separator);
      }
      return options.colonNotation ? result.join("") : result.join(" ");
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReadingProgress
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var RT_DEFAULT_SETTINGS = {
  readingSpeed: 300,
  format: "default" /* Default */,
  appendText: "left",
  showProgressPercentage: true,
  showOnMobile: true,
  hideOtherStatusBarItemsOnMobile: true
};
var ReadingTimeSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Reading speed").setDesc("Words per minute used for reading speed (default: 200).").addText((text) => {
      text.setPlaceholder("Example: 200").setValue(this.plugin.settings.readingSpeed.toString()).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.readingSpeed = parseInt(value.trim());
        yield this.plugin.saveSettings().then(this.plugin.calculateReadingTime);
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("Format").setDesc("Choose the output format").addDropdown(
      (dropdown) => dropdown.addOption("default" /* Default */, "Default (10m)").addOption("compact" /* Compact */, "Compact (10 min)").addOption("simple" /* Simple */, "Simple (10m 4s)").addOption(
        "verbose" /* Verbose */,
        "Verbose (10 minutes 4 seconds)"
      ).addOption("digital" /* Digital */, "Colon notation (10:04)").setValue(this.plugin.settings.format).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.format = value;
        yield this.plugin.saveSettings().then(this.plugin.calculateReadingTime);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Append text").setDesc("Append 'left' to formatted string.").addText(
      (text) => text.setValue(this.plugin.settings.appendText).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.appendText = value.trim();
        yield this.plugin.saveSettings().then(this.plugin.calculateReadingTime);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Show reading progress percentage").setDesc("Display percentage of text read").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showProgressPercentage).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showProgressPercentage = value;
        yield this.plugin.saveSettings().then(this.plugin.calculateReadingTime);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Show on mobile").setDesc(
      "Obsidian hides the status bar on mobile by default. Turn this on to show the reading progress pill at the bottom of the screen."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showOnMobile).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showOnMobile = value;
        yield this.plugin.saveSettings();
        this.plugin.applyMobileClasses();
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Hide other status bar items on mobile").setDesc(
      "When the mobile pill is visible, hide other status bar items (backlinks, properties, word count, etc.) so only the reading time shows. Has no effect when 'Show on mobile' is off."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hideOtherStatusBarItemsOnMobile).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.hideOtherStatusBarItemsOnMobile = value;
        yield this.plugin.saveSettings();
        this.plugin.applyMobileClasses();
      }))
    );
  }
};

// src/helpers.ts
var import_pretty_ms = __toESM(require_pretty_ms());
function readingTimeText(text, plugin) {
  const charCount = text.replace(/[\s\p{P}]+/gu, "").length;
  const wordsPerMinute = plugin.settings.readingSpeed || 200;
  const charsPerMinute = wordsPerMinute * 5;
  const minutesFloat = charsPerMinute > 0 ? charCount / charsPerMinute : 0;
  const timeMs = Math.round(minutesFloat * 60 * 1e3);
  if (timeMs < 6e4) {
    return plugin.settings.appendText ? `0 min ${plugin.settings.appendText}` : `0 min`;
  }
  const minutes = Math.ceil(minutesFloat);
  let options = { secondsDecimalDigits: 0 };
  switch (plugin.settings.format) {
    case "simple" /* Simple */:
      break;
    case "default" /* Default */:
      if (timeMs > 36e5) {
        options = __spreadProps(__spreadValues({}, options), { unitCount: 2 });
      } else {
        options = __spreadProps(__spreadValues({}, options), { compact: true });
      }
      break;
    case "verbose" /* Verbose */:
      options = __spreadProps(__spreadValues({}, options), { verbose: true });
      break;
    case "digital" /* Digital */:
      options = __spreadProps(__spreadValues({}, options), { colonNotation: true });
      break;
    case "compact" /* Compact */:
    default:
      return plugin.settings.appendText ? `${minutes} min left` : `${minutes} min`;
  }
  const output = (0, import_pretty_ms.default)(timeMs, options);
  return plugin.settings.appendText ? `${output} ${plugin.settings.appendText}` : output;
}

// src/main.ts
var ReadingProgress = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.calculateReadingTime = () => {
      const mdView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      if (!mdView) {
        this.statusBar.setText("0 min left");
        return;
      }
      const scrollEl = this.getScrollEl(mdView);
      if (!scrollEl) {
        this.statusBar.setText("0 min left");
        return;
      }
      const scrollTop = scrollEl.scrollTop;
      const scrollHeight = scrollEl.scrollHeight;
      const clientHeight = scrollEl.clientHeight;
      const denom = scrollHeight - clientHeight;
      const progress = denom > 0 ? scrollTop / denom : 0;
      const scrollProgress = Math.min(100, parseFloat((progress * 100).toFixed(1)));
      const totalText = typeof mdView.getViewData === "function" ? mdView.getViewData() : mdView.editor ? mdView.editor.getValue() : "";
      const estimatedReadPosition = Math.floor(totalText.length * progress);
      const textBelowScroll = totalText.slice(estimatedReadPosition);
      const result = readingTimeText(textBelowScroll, this);
      let statusText = `${result}`;
      if (this.settings.showProgressPercentage) {
        statusText += ` (${scrollProgress}%)`;
      }
      this.statusBar.setText(statusText);
    };
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.statusBar = this.addStatusBarItem();
      this.statusBar.addClass("plugin-reading-progress");
      this.statusBar.setText("");
      this.applyMobileClasses();
      this.addSettingTab(new ReadingTimeSettingsTab(this.app, this));
      this.addCommand({
        id: "reading-time-editor",
        name: "Selected text",
        editorCallback: (editor, view) => {
          new ReadingTimeModal(this.app, editor, this).open();
        }
      });
      this.registerEvent(
        this.app.workspace.on("layout-change", this.calculateReadingTime)
      );
      this.registerEvent(
        this.app.workspace.on("file-open", this.calculateReadingTime)
      );
      this.registerEvent(
        this.app.workspace.on("active-leaf-change", this.calculateReadingTime)
      );
      this.registerEvent(
        this.app.workspace.on(
          "editor-change",
          (0, import_obsidian2.debounce)(this.calculateReadingTime, 500)
        )
      );
      let lastScrollTop = null;
      this.registerInterval(
        window.setInterval(() => {
          const mdView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
          if (!mdView)
            return;
          const scrollEl = this.getScrollEl(mdView);
          if (scrollEl) {
            const scrollTop = scrollEl.scrollTop;
            if (lastScrollTop === null || scrollTop !== lastScrollTop) {
              lastScrollTop = scrollTop;
              this.calculateReadingTime();
            }
          }
        }, 500)
      );
    });
  }
  getScrollEl(mdView) {
    var _a, _b, _c;
    const isPreview = mdView.getMode && mdView.getMode() === "preview";
    if (isPreview) {
      return (_a = mdView.contentEl.querySelector(".markdown-preview-view")) != null ? _a : mdView.contentEl;
    }
    return (_c = (_b = mdView.contentEl.querySelector(".cm-scroller")) != null ? _b : mdView.contentEl.querySelector(".markdown-source-view")) != null ? _c : mdView.contentEl;
  }
  applyMobileClasses() {
    document.body.toggleClass(
      "reading-progress-mobile-visible",
      this.settings.showOnMobile
    );
    document.body.toggleClass(
      "reading-progress-mobile-hide-others",
      this.settings.showOnMobile && this.settings.hideOtherStatusBarItemsOnMobile
    );
  }
  onunload() {
    document.body.removeClass("reading-progress-mobile-visible");
    document.body.removeClass("reading-progress-mobile-hide-others");
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign(
        {},
        RT_DEFAULT_SETTINGS,
        yield this.loadData()
      );
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
var ReadingTimeModal = class extends import_obsidian2.Modal {
  constructor(app, editor, plugin) {
    super(app);
    this.editor = editor;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Reading time");
    const stats = readingTimeText(this.editor.getSelection(), this.plugin);
    contentEl.setText(`${stats} (at ${this.plugin.settings.readingSpeed} wpm)`);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
